config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque'
  resources :people
  get '/about' => 'pages#about'
  root to: 'people#index'
end

# == Route Map
#
#      Prefix Verb   URI Pattern                Controller#Action
#      people GET    /people(.:format)          people#index
#             POST   /people(.:format)          people#create
#  new_person GET    /people/new(.:format)      people#new
# edit_person GET    /people/:id/edit(.:format) people#edit
#      person GET    /people/:id(.:format)      people#show
#             PATCH  /people/:id(.:format)      people#update
#             PUT    /people/:id(.:format)      people#update
#             DELETE /people/:id(.:format)      people#destroy
#       about GET    /about(.:format)           pages#about
#        root GET    /                          people#index
#

app/models/person.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(254)
#  job        :string(255)
#  bio        :text(65535)
#  gender     :string(255)
#  birthdate  :date
#  picture    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# Person Model
class Person < ActiveRecord::Base
  # Constants
  GENDER = %w(male female).freeze
  EMAIL_REGEX = /\A[^@]+@[^@]+\z/
  DEFAULT_PICTURE = ActionController::Base.helpers.image_path('default-picture.png')

  # Validations
  validates :first_name, presence: true
  validates :first_name, length: { maximum: 75 }

  validates :last_name, presence: true
  validates :last_name, length: { maximum: 75 }

  validates :email, presence: true
  validates :email, length: { maximum: 254 }
  validates :email, uniqueness: true
  validates :email, format: { with: EMAIL_REGEX }

  validates :job, length: { maximum: 75 }, allow_nil: true

  validates :gender, presence: true
  validates :gender, inclusion: GENDER

  validates :birthdate, presence: true
  validates :birthdate, cannot_accept_futures_dates: true, if: 'birthdate.present?'

  # Scopes
  scope :people_to_notify, -> (id) { where.not(id: id) }

  # Callbacks
  after_create :notify_create_to_all

  private

  def notify_create_to_all
    Resque.enqueue(PersonNotificator, :create, id, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
# Application controller base class
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Pages controller class
class PagesController < ApplicationController
  def about
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

# People controller class
class PeopleController < ApplicationController
  before_action :current_person, only: [:edit, :update, :show, :destroy]

  def index
    @people = Person.all.order(first_name: :asc, last_name: :asc)
                    .paginate(page: params[:page], per_page: 6)
                    .decorate
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      message = { success: I18n.t('controllers.people.create') }
      redirect_to person_path(@person), flash: message
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @person.update(person_params)
      message = { notice: I18n.t('controllers.people.update') }
      redirect_to person_path(@person), flash: message
    else
      render :edit
    end
  end

  def destroy
    deleted_person = { full_name: @person.full_name }
    @person.destroy
    Resque.enqueue(PersonNotificator, :delete, nil, deleted_person)
    message = { success: I18n.t('controllers.people.destroy') }
    redirect_to people_path, flash: message
  end

  private

  def current_person
    @person ||= PersonDecorator.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :job, :bio,
                                   :gender, :birthdate, :picture)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
# Application helper
module ApplicationHelper
  # Flash messages classes
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error:   'alert-danger',
    alert:   'alert-warning',
    notice:  'alert-success',
    info:    'alert-info'
  }.freeze

  def alert_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG[flash_type.to_sym]
  end

  def error_messages(resource)
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map{ |msg| content_tag(:li, msg)}.join
    html = <<-HTML
    <div class="alert alert-danger media fade in"><ul>#{messages}</ul></div>
    HTML
    html.html_safe
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title People Management System
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/navigation'
    #flash_messages
      = render "shared/flash", flash: flash

    - if controller.controller_name == 'pages' && controller.action_name == 'about'
      = yield
    - else
      .container
        = yield
    %hr
    = render 'shared/footer'

  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = yield :javascript

app/views/pages/about.html.haml
%section#about.success
  .container
    .row
      .col-lg-12.text-center
        %h2 About
        %hr.star-light

    .row
      .col-lg-12.text-center
        %p People Management System (PMS) is a RoR application - programming test proposed by GAP to manage people through CRUD (basics functions: list, create, update and delete persons) operations. Also have a notification system that allows notify all people via email when some person has been created or deleted.
    .row
      .col-lg-8.col-lg-offset-2.text-center
        %a.btn.btn-outline{ href: 'https://luisdgutierrez05@bitbucket.org/luisdgutierrez05/people-management.git' }
          %i.fa.fa-download
          Source Code
    %br
    .row
      .col-lg-8.col-lg-offset-2.text-center
        %h5
          Developed by Luis David Gutierrez
        %a.btn-social.btn-outline{ href: 'https://co.linkedin.com/in/luisd05' }
          %i.fa.fa-fw.fa-linkedin
        %a.btn-social.btn-outline{ href: 'https://twitter.com/luisd0510' }
          %i.fa.fa-fw.fa-twitter

app/views/people/_form.html.haml
%section
  .container
    .row
      .col-lg-12.text-center
        %h2= title
        %hr.star-primary
    .row
      .col-lg-8.col-lg-offset-2
        = form_for person do |f|
          = error_messages(person)
          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :first_name, class: 'control-label'
              = f.text_field :first_name, class: 'form-control', placeholder: 'First Name', autofocus: true, require: true
              %p.help-block.text-danger

          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :last_name, class: 'control-label'
              = f.text_field :last_name, class: 'form-control', placeholder: 'Last Name'
              %p.help-block.text-danger
          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :email, class: 'control-label'
              = f.email_field :email, class: 'form-control', placeholder: 'Email'
              %p.help-block.text-danger
          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :job, class: 'control-label'
              = f.text_field :job, class: 'form-control', placeholder: 'Job'

          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :gender, class: 'control-label'
              = f.select :gender, Person::GENDER, { include_blank: 'Select a gender' }, class: 'form-control'

          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :bio, class: 'control-label'
              = f.text_area :bio, class: 'form-control', placeholder: 'Bio'

          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :picture, class: 'control-label'
              = f.text_field :picture, class: 'form-control', placeholder: 'Picture'

          .row.control-group
            .form-group.col-xs-12.floating-label-form-group.controls
              = f.label :birthdate, class: 'control-label'
              = f.date_field :birthdate, class: 'form-control input-lg normal-font-size', value: @person.birthdate
          %br
          .row
            .form-group.col-xs-12
              = f.submit 'Save', class: 'btn btn-success'
              = link_to 'Cancel', cancel_action, class: 'btn btn-default'

app/views/people/edit.html.haml
.row
  .col-sm-8
    .panel
      = render 'form', person: @person, title: 'Edit Person', cancel_action: person_path(@person)

app/views/people/index.html.haml
.row
  .col-lg-12
    %h1 Welcome
    %hr

- if @people.empty?
  .row
    .col-lg-12
    No people please create a new one
    = link_to 'Add Person', new_person_path, class: 'btn btn-success'

- else

.row
  .col-lg-12
    - @people.each do |person|
      .col-lg-4.col-sm-6.text-center
        %img.img-circle.img-responsive.img-center{ src: person.picture, width: '100', height: '100' }
        %h5= link_to person.full_name, person_path(person)
        %h5= person.email
        %h5
          Age:
          = person.age

        = link_to person_path(person), method: :delete, data: { confirm: "Are you sure you want to delete '#{person.full_name}'?"} do
          Delete
          %i.fa.fa-fw.fa-trash

    .text-center
      = will_paginate @people

app/views/people/new.html.haml
.row
  .col-sm-8
    .panel
      = render 'form', person: @person, title: 'Create Person', cancel_action: people_path

app/views/people/show.html.haml
%section
  .container
    .row
      .col-lg-12.text-center
        %h2= @person.full_name
        %hr.star-primary
        %img.img-circle.img-responsive.img-center{ src: @person.picture, width: '200', height: '200' }
        %h3
          = @person.job_titleize
          %span{ class: 'js-tooltip', 'data-original-title' => "#{@person.gender_titleize}", 'data-placement' => 'top', 'data-toggle' => 'tooltip' }
            %i{ class: "fa fa-fw fa-#{@person.gender_icon_name}" }
        %h5
          Email:
          = @person.email
        %h5
          Birthdate:
          = @person.birthdate_formatted
          %i{ class: "fa fa-fw fa-birthday-cake" }

    - if @person.bio?
      .row
        .col-lg-8.col-lg-offset-2.tex-center

          %h5.biography-content
            %b Bio:
            %br
            = @person.bio
    %hr
    .row
      .col-lg-12.text-center
        = link_to 'Back', people_path, class: 'btn btn-default'
        = link_to 'Edit', edit_person_path(@person), class: 'btn btn-primary'
        = link_to 'Delete', person_path(@person), method: :delete, data: { confirm: "Are you sure you want to delete '#{@person.full_name}'?"}, class: 'btn btn-danger'

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  %div#flash_messages{ class: "alert #{alert_class_for(type)} alert-dismissible fade in alert-page"}
    %button.close{'data-dismiss' => 'alert', type: 'button'}
      %i.fa.fa-times-circle
    = message

app/views/shared/_footer.html.haml
%footer
  .footer-below
    .container
      .row
        .col-lg-12
          = "Copyright © People Management #{Date.today.year}"

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .container
    .navbar-header
      %a.navbar-brand{ href: root_path } People Management System
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.page-scroll
          = link_to 'Add Person', new_person_path
        %li.page-scroll
          %a{ href: about_path } About